### ISSUE TITLE
Avoid including when bundling

### ISSUE THREAD

**Issue by jcbhmr** [jimmywarting/node-domexception#6]
![image](https://github.com/jimmywarting/node-domexception/assets/61068799/cfbb312d-217e-4f05-b4ef-1608038a621c)

Demo https://stackblitz.com/edit/vitejs-vite-1ujgca?file=main.js,dist%2Fassets%2Findex-3fe401ab.js&terminal=dev

Right now when you bundle code that uses this, there is no special browser path that avoids this Node.js specific polyfill. I think adding export conditions to make it so that this is a zero-cost polyfill when bundling for HTML is a good idea.

**Comment by jimmywarting** [comment]
i have switched to only having the export-less atob solution so that's just a polyfill now that do not depend on worker_threads.
I didn't think it was worth it to have it being both a ponyfill and a polyfill.

having it as a polyfill only means that both cjs and esm can import/require it without an issue with it being a ESM only package

fixed/released in v2.x
